//
//  S2MCalloutAnnotation.h
//  Example
//
//  Created by Joern Ehmann on 10/12/14.
//  Copyright (c) 2014 SinnerSchrader Mobile. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <MapKit/MapKit.h>

/**
 Annotation class, to implement custom Annotation Callout views
 */
@interface S2MCalloutAnnotation : NSObject <MKAnnotation>

/**
 *  designated initializer to match Annotation protocol
 *
 *  @param annotation
 *
 *  @return S2MCalloutAnnotation instance
 */
-(instancetype)initWithAnnotation:(id<MKAnnotation>)annotation;

/**
 *  coordinate of the annotation
 */
@property (nonatomic, assign) CLLocationCoordinate2D coordinate;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSString *subtitle;

/**
 *  assignable property. Set value to have autogenerated subtitle in km of distance
 */
@property (nonatomic, strong) NSNumber* distanceInMeter;


@end